services:
  nginx-rtmp:
    network_mode: service:ts-rtmp
    ports: []  # Disable published ports
    depends_on:
      ts-rtmp:
        condition: service_healthy

  ts-rtmp:
    image: tailscale/tailscale:latest
    hostname: rtmp
    environment:
      - TS_AUTHKEY=${HEADSCALE_AUTHKEY}
      - TS_USERSPACE=true
      - TS_EXTRA_ARGS=--login-server=${HEADSCALE_TAILNET} --accept-routes --advertise-tags=${HEADSCALE_TAG} --accept-dns
      - TS_DEBUG_TUN_NAME=ts-rtmp
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - tailscale-rtmp:/var/lib/tailscale
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "tailscale", "status", "--active"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  tailscale-rtmp:

