services:
  cmake-app:
    build: .
    volumes:
      - .:/receiver  # Mount current directory to /app in container
    working_dir: /receiver
    # Optional environment variables
    environment:
      - CMAKE_BUILD_TYPE=Release
    restart: unless-stopped
    network_mode: host
