services:
  cmake-app:
    build: .
    volumes:
      - .:/sender  # Mount current directory to /app in container
    working_dir: /sender
    # Optional environment variables
    network_mode: host
    environment:
      - CMAKE_BUILD_TYPE=Release
      - WS_SERVER_IP=${WS_SERVER_IP}
      - WS_SERVER_PORT=${WS_SERVER_PORT}
